### ISSUE TITLE
French version

### ISSUE THREAD

**Issue by Martoni** [soburi/zephyr_porting_gd32v#1]
Hi @soburi 
I just translated your tutorial in french [here](https://github.com/Martoni/zephyr_porting_gd32v/tree/french_version).
I'm greatly interested by zephyr and wanted to try it with longan nano. Then your tutorial is exactly what I'm looking for... but it was in Japanese ;)

It's mainly automatic translation, with some  corrections from mine.

**Comment by soburi** [comment]
Merci pour la traduction!

Bit update on my repository to create more readable GitHub Pages, and link your translation.
https://soburi.github.io/zephyr_porting_gd32v/

(simply add SUMMARY.md for ToC, and run `gitbook build . docs`)

**Comment by Martoni** [comment]
Thanks, it's not a very good translation in fact.
But I can't read japonese then this automatic translation was a minimum to understand the tutorial :)
